// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemRequestKPU.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401111530_datafail")]
    partial class datafail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Complex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Complexes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Площадка ГКС",
                            Name = "Газокомпрессорная станция",
                            Type = "ГКС"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Площадка ГРС",
                            Name = "Газораспределительная станция",
                            Type = "ГРС"
                        });
                });

            modelBuilder.Entity("EquipmentInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("FactoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicalNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TechnicalObjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("TechnologicalUnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("TechnicalObjectId");

                    b.HasIndex("TechnologicalUnitId");

                    b.ToTable("EquipmentInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStatus = "",
                            EquipmentTypeId = 1,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.1-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            CurrentStatus = "",
                            EquipmentTypeId = 2,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.1-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            CurrentStatus = "",
                            EquipmentTypeId = 3,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.1-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            CurrentStatus = "",
                            EquipmentTypeId = 4,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.1-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        },
                        new
                        {
                            Id = 5,
                            CurrentStatus = "",
                            EquipmentTypeId = 5,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.1-005",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        },
                        new
                        {
                            Id = 6,
                            CurrentStatus = "",
                            EquipmentTypeId = 6,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.1-006",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        },
                        new
                        {
                            Id = 7,
                            CurrentStatus = "",
                            EquipmentTypeId = 1,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.2-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 2
                        },
                        new
                        {
                            Id = 8,
                            CurrentStatus = "",
                            EquipmentTypeId = 2,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.2-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 2
                        },
                        new
                        {
                            Id = 9,
                            CurrentStatus = "",
                            EquipmentTypeId = 3,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.2-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 2
                        },
                        new
                        {
                            Id = 10,
                            CurrentStatus = "",
                            EquipmentTypeId = 4,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.2-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 2
                        },
                        new
                        {
                            Id = 11,
                            CurrentStatus = "",
                            EquipmentTypeId = 5,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.2-005",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 2
                        },
                        new
                        {
                            Id = 12,
                            CurrentStatus = "",
                            EquipmentTypeId = 6,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.2-006",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 2
                        },
                        new
                        {
                            Id = 13,
                            CurrentStatus = "",
                            EquipmentTypeId = 1,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.1-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 3
                        },
                        new
                        {
                            Id = 14,
                            CurrentStatus = "",
                            EquipmentTypeId = 2,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.1-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 3
                        },
                        new
                        {
                            Id = 15,
                            CurrentStatus = "",
                            EquipmentTypeId = 3,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.1-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 3
                        },
                        new
                        {
                            Id = 16,
                            CurrentStatus = "",
                            EquipmentTypeId = 4,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.1-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 3
                        },
                        new
                        {
                            Id = 17,
                            CurrentStatus = "",
                            EquipmentTypeId = 5,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.1-005",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 3
                        },
                        new
                        {
                            Id = 18,
                            CurrentStatus = "",
                            EquipmentTypeId = 6,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.1-006",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 3
                        },
                        new
                        {
                            Id = 19,
                            CurrentStatus = "",
                            EquipmentTypeId = 1,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.2-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 4
                        },
                        new
                        {
                            Id = 20,
                            CurrentStatus = "",
                            EquipmentTypeId = 2,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.2-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 4
                        },
                        new
                        {
                            Id = 21,
                            CurrentStatus = "",
                            EquipmentTypeId = 3,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.2-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 4
                        },
                        new
                        {
                            Id = 22,
                            CurrentStatus = "",
                            EquipmentTypeId = 4,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.2-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 4
                        },
                        new
                        {
                            Id = 23,
                            CurrentStatus = "",
                            EquipmentTypeId = 5,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.2-005",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 4
                        },
                        new
                        {
                            Id = 24,
                            CurrentStatus = "",
                            EquipmentTypeId = 6,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА2.2-006",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 4
                        },
                        new
                        {
                            Id = 25,
                            CurrentStatus = "",
                            EquipmentTypeId = 1,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.1-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 5
                        },
                        new
                        {
                            Id = 26,
                            CurrentStatus = "",
                            EquipmentTypeId = 2,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.1-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 5
                        },
                        new
                        {
                            Id = 27,
                            CurrentStatus = "",
                            EquipmentTypeId = 3,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.1-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 5
                        },
                        new
                        {
                            Id = 28,
                            CurrentStatus = "",
                            EquipmentTypeId = 4,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.1-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 5
                        },
                        new
                        {
                            Id = 29,
                            CurrentStatus = "",
                            EquipmentTypeId = 5,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.1-005",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 5
                        },
                        new
                        {
                            Id = 30,
                            CurrentStatus = "",
                            EquipmentTypeId = 6,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.1-006",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 5
                        },
                        new
                        {
                            Id = 31,
                            CurrentStatus = "",
                            EquipmentTypeId = 1,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.2-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 6
                        },
                        new
                        {
                            Id = 32,
                            CurrentStatus = "",
                            EquipmentTypeId = 2,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.2-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 6
                        },
                        new
                        {
                            Id = 33,
                            CurrentStatus = "",
                            EquipmentTypeId = 3,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.2-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 6
                        },
                        new
                        {
                            Id = 34,
                            CurrentStatus = "",
                            EquipmentTypeId = 4,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.2-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 6
                        },
                        new
                        {
                            Id = 35,
                            CurrentStatus = "",
                            EquipmentTypeId = 5,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.2-005",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 6
                        },
                        new
                        {
                            Id = 36,
                            CurrentStatus = "",
                            EquipmentTypeId = 6,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА3.2-006",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 6
                        },
                        new
                        {
                            Id = 37,
                            CurrentStatus = "",
                            EquipmentTypeId = 7,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УОГ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 7
                        },
                        new
                        {
                            Id = 38,
                            CurrentStatus = "",
                            EquipmentTypeId = 8,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УОГ-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 7
                        },
                        new
                        {
                            Id = 39,
                            CurrentStatus = "",
                            EquipmentTypeId = 9,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УОГ-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 7
                        },
                        new
                        {
                            Id = 40,
                            CurrentStatus = "",
                            EquipmentTypeId = 10,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УРГ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 8
                        },
                        new
                        {
                            Id = 41,
                            CurrentStatus = "",
                            EquipmentTypeId = 11,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УРГ-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 8
                        },
                        new
                        {
                            Id = 42,
                            CurrentStatus = "",
                            EquipmentTypeId = 12,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УРГ-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 8
                        },
                        new
                        {
                            Id = 43,
                            CurrentStatus = "",
                            EquipmentTypeId = 13,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УРГ-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 8
                        },
                        new
                        {
                            Id = 44,
                            CurrentStatus = "",
                            EquipmentTypeId = 14,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УПОГ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 9
                        },
                        new
                        {
                            Id = 45,
                            CurrentStatus = "",
                            EquipmentTypeId = 15,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УПОГ-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 9
                        },
                        new
                        {
                            Id = 46,
                            CurrentStatus = "",
                            EquipmentTypeId = 16,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УПОГ-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 9
                        },
                        new
                        {
                            Id = 47,
                            CurrentStatus = "",
                            EquipmentTypeId = 13,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС1-УПОГ-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 9
                        },
                        new
                        {
                            Id = 48,
                            CurrentStatus = "",
                            EquipmentTypeId = 7,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УОГ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 10
                        },
                        new
                        {
                            Id = 49,
                            CurrentStatus = "",
                            EquipmentTypeId = 8,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УОГ-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 10
                        },
                        new
                        {
                            Id = 50,
                            CurrentStatus = "",
                            EquipmentTypeId = 9,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УОГ-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 10
                        },
                        new
                        {
                            Id = 51,
                            CurrentStatus = "",
                            EquipmentTypeId = 10,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УРГ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 11
                        },
                        new
                        {
                            Id = 52,
                            CurrentStatus = "",
                            EquipmentTypeId = 11,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УРГ-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 11
                        },
                        new
                        {
                            Id = 53,
                            CurrentStatus = "",
                            EquipmentTypeId = 12,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УРГ-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 11
                        },
                        new
                        {
                            Id = 54,
                            CurrentStatus = "",
                            EquipmentTypeId = 13,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УРГ-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 11
                        },
                        new
                        {
                            Id = 55,
                            CurrentStatus = "",
                            EquipmentTypeId = 14,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УПОГ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 12
                        },
                        new
                        {
                            Id = 56,
                            CurrentStatus = "",
                            EquipmentTypeId = 15,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УПОГ-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 12
                        },
                        new
                        {
                            Id = 57,
                            CurrentStatus = "",
                            EquipmentTypeId = 16,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УПОГ-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 12
                        },
                        new
                        {
                            Id = 58,
                            CurrentStatus = "",
                            EquipmentTypeId = 13,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС2-УПОГ-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 12
                        },
                        new
                        {
                            Id = 59,
                            CurrentStatus = "",
                            EquipmentTypeId = 7,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УОГ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 13
                        },
                        new
                        {
                            Id = 60,
                            CurrentStatus = "",
                            EquipmentTypeId = 8,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УОГ-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 13
                        },
                        new
                        {
                            Id = 61,
                            CurrentStatus = "",
                            EquipmentTypeId = 9,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УОГ-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 13
                        },
                        new
                        {
                            Id = 62,
                            CurrentStatus = "",
                            EquipmentTypeId = 10,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УРГ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 14
                        },
                        new
                        {
                            Id = 63,
                            CurrentStatus = "",
                            EquipmentTypeId = 11,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УРГ-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 14
                        },
                        new
                        {
                            Id = 64,
                            CurrentStatus = "",
                            EquipmentTypeId = 12,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УРГ-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 14
                        },
                        new
                        {
                            Id = 65,
                            CurrentStatus = "",
                            EquipmentTypeId = 13,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УРГ-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 14
                        },
                        new
                        {
                            Id = 66,
                            CurrentStatus = "",
                            EquipmentTypeId = 14,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УПОГ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 15
                        },
                        new
                        {
                            Id = 67,
                            CurrentStatus = "",
                            EquipmentTypeId = 15,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УПОГ-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 15
                        },
                        new
                        {
                            Id = 68,
                            CurrentStatus = "",
                            EquipmentTypeId = 16,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УПОГ-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 15
                        },
                        new
                        {
                            Id = 69,
                            CurrentStatus = "",
                            EquipmentTypeId = 13,
                            FactoryNumber = "",
                            InventoryNumber = "ГРС3-УПОГ-004",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 2,
                            TechnologicalUnitId = 15
                        });
                });

            modelBuilder.Entity("EquipmentParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccuracyClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipmentInstanceId")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<string>("MeasurementRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("NormalValue")
                        .HasColumnType("double precision");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentInstanceId");

                    b.ToTable("EquipmentParameters");
                });

            modelBuilder.Entity("EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "KPU",
                            Model = "CTRL-MAIN",
                            Name = "Главный контроллер управления",
                            Specifications = "Контроллер"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "KPU",
                            Model = "ASU",
                            Name = "Система автоматического управления",
                            Specifications = "АСУ"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "KPU",
                            Model = "RPM-TURB",
                            Name = "Датчик оборотов двигателя основной турбины",
                            Specifications = "Датчик оборотов"
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "KPU",
                            Model = "TEMP-TURB",
                            Name = "Датчик температуры основной турбины",
                            Specifications = "Датчик температуры"
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "KPU",
                            Model = "RPM-COMP",
                            Name = "Датчик оборотов нагнетателя",
                            Specifications = "Датчик оборотов"
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "KPU",
                            Model = "AUX",
                            Name = "Вспомогательное оборудование",
                            Specifications = "Вспомогательное"
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "KPU",
                            Model = "PRESS-FILTER",
                            Name = "Датчик давления основного фильтра",
                            Specifications = "Датчик давления"
                        },
                        new
                        {
                            Id = 8,
                            Manufacturer = "KPU",
                            Model = "PRESS-IN",
                            Name = "Датчик давления на входе",
                            Specifications = "Датчик давления"
                        },
                        new
                        {
                            Id = 9,
                            Manufacturer = "KPU",
                            Model = "TEMP-IN",
                            Name = "Датчик температуры на входе",
                            Specifications = "Датчик температуры"
                        },
                        new
                        {
                            Id = 10,
                            Manufacturer = "KPU",
                            Model = "PRESS-REG",
                            Name = "Датчик регулятора давления",
                            Specifications = "Датчик давления"
                        },
                        new
                        {
                            Id = 11,
                            Manufacturer = "KPU",
                            Model = "VIB-REG",
                            Name = "Датчик вибрации регулятора",
                            Specifications = "Датчик вибрации"
                        },
                        new
                        {
                            Id = 12,
                            Manufacturer = "KPU",
                            Model = "TEMP-REG",
                            Name = "Датчик температуры регулятора",
                            Specifications = "Датчик температуры"
                        },
                        new
                        {
                            Id = 13,
                            Manufacturer = "KPU",
                            Model = "CTRL-BOARD",
                            Name = "Контроллер платы управления",
                            Specifications = "Контроллер"
                        },
                        new
                        {
                            Id = 14,
                            Manufacturer = "KPU",
                            Model = "TEMP-HEATER",
                            Name = "Датчик температуры подогревателя",
                            Specifications = "Датчик температуры"
                        },
                        new
                        {
                            Id = 15,
                            Manufacturer = "KPU",
                            Model = "FLAME",
                            Name = "Датчик наличия пламени",
                            Specifications = "Датчик пламени"
                        },
                        new
                        {
                            Id = 16,
                            Manufacturer = "KPU",
                            Model = "ODOR-LEVEL",
                            Name = "Датчик уровня расхода одоранта",
                            Specifications = "Датчик уровня"
                        });
                });

            modelBuilder.Entity("SistemRequestKPU.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TechnicalObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplexId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGRS")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("TechnicalObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComplexId = 1,
                            IsGRS = false,
                            Name = "Газокомпрессорная станция",
                            ObjectType = "ГКС"
                        },
                        new
                        {
                            Id = 2,
                            ComplexId = 2,
                            IsGRS = false,
                            Name = "Газораспределительная станция",
                            ObjectType = "ГРС"
                        });
                });

            modelBuilder.Entity("TechnologicalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TechnicalObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalObjectId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("TechnologicalUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ГПА-1.1",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №1.1",
                            TechnicalObjectId = 1,
                            WorkshopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "ГПА-1.2",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №1.2",
                            TechnicalObjectId = 1,
                            WorkshopId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "ГПА-2.1",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №2.1",
                            TechnicalObjectId = 1,
                            WorkshopId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "ГПА-2.2",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №2.2",
                            TechnicalObjectId = 1,
                            WorkshopId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "ГПА-3.1",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №3.1",
                            TechnicalObjectId = 1,
                            WorkshopId = 3
                        },
                        new
                        {
                            Id = 6,
                            Code = "ГПА-3.2",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №3.2",
                            TechnicalObjectId = 1,
                            WorkshopId = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "УОГ-1",
                            Description = "",
                            Name = "Узел очистки газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 4
                        },
                        new
                        {
                            Id = 8,
                            Code = "УРГ-1",
                            Description = "",
                            Name = "Узел редуцирования газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 4
                        },
                        new
                        {
                            Id = 9,
                            Code = "УПОГ-1",
                            Description = "",
                            Name = "Узел подогрева и одоризации газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 4
                        },
                        new
                        {
                            Id = 10,
                            Code = "УОГ-2",
                            Description = "",
                            Name = "Узел очистки газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 5
                        },
                        new
                        {
                            Id = 11,
                            Code = "УРГ-2",
                            Description = "",
                            Name = "Узел редуцирования газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 5
                        },
                        new
                        {
                            Id = 12,
                            Code = "УПОГ-2",
                            Description = "",
                            Name = "Узел подогрева и одоризации газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 5
                        },
                        new
                        {
                            Id = 13,
                            Code = "УОГ-3",
                            Description = "",
                            Name = "Узел очистки газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 6
                        },
                        new
                        {
                            Id = 14,
                            Code = "УРГ-3",
                            Description = "",
                            Name = "Узел редуцирования газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 6
                        },
                        new
                        {
                            Id = 15,
                            Code = "УПОГ-3",
                            Description = "",
                            Name = "Узел подогрева и одоризации газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 6
                        });
                });

            modelBuilder.Entity("Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponsiblePersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsiblePersonId");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "КЦ1",
                            Name = "Компрессорный цех №1",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "КЦ2",
                            Name = "Компрессорный цех №2",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "КЦ3",
                            Name = "Компрессорный цех №3",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "ГРС1",
                            Name = "ГРС №1",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "ГРС2",
                            Name = "ГРС №2",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "ГРС3",
                            Name = "ГРС №3",
                            ResponsiblePersonId = 1
                        });
                });

            modelBuilder.Entity("kursovou_wed.models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicalSpecs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TechnologicalUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkType")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EquipmentInstanceId");

                    b.HasIndex("TechnicalObjectId");

                    b.HasIndex("TechnologicalUnitId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("kursovou_wed.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$RdP4N9/ic6c22zNIFDry5OV9lArcoiWYhxAaTlvia/oShaja2gGwy",
                            Role = 3,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "dispatcher@example.com",
                            PasswordHash = "$2a$11$JS3m9UoF9XzBMx9OPk3.c.Eh7Wfk6pwqAtb7AY7e0g/uimS/hSrRy",
                            Role = 2,
                            Username = "dispatcher"
                        },
                        new
                        {
                            Id = 3,
                            Email = "executor1@example.com",
                            PasswordHash = "$2a$11$N.zPWI4RnJ2X1hmEhZJj5O9bTZZ9ohiW6L0k4cFwiM22ptwmjhHem",
                            Role = 1,
                            Username = "executor1"
                        },
                        new
                        {
                            Id = 4,
                            Email = "executor2@example.com",
                            PasswordHash = "$2a$11$BmVM91CKi9BFK/UcocMCI..Co.Psf6gx2o/ieK.AAPXvtJt7jCmLq",
                            Role = 1,
                            Username = "executor2"
                        },
                        new
                        {
                            Id = 5,
                            Email = "applicant@example.com",
                            PasswordHash = "$2a$11$ohOk23FnBCHoI86p9ZmnHujdTYY.mha3JYr6ITiPqhanwxh04D.Dm",
                            Role = 0,
                            Username = "applicant"
                        });
                });

            modelBuilder.Entity("EquipmentInstance", b =>
                {
                    b.HasOne("EquipmentType", "EquipmentType")
                        .WithMany("Instances")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalObject", "TechnicalObject")
                        .WithMany("EquipmentInstances")
                        .HasForeignKey("TechnicalObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TechnologicalUnit", "TechnologicalUnit")
                        .WithMany("EquipmentInstances")
                        .HasForeignKey("TechnologicalUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipmentType");

                    b.Navigation("TechnicalObject");

                    b.Navigation("TechnologicalUnit");
                });

            modelBuilder.Entity("EquipmentParameter", b =>
                {
                    b.HasOne("EquipmentInstance", "EquipmentInstance")
                        .WithMany("Parameters")
                        .HasForeignKey("EquipmentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentInstance");
                });

            modelBuilder.Entity("TechnicalObject", b =>
                {
                    b.HasOne("Complex", "Complex")
                        .WithMany("TechnicalObjects")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("TechnologicalUnit", b =>
                {
                    b.HasOne("TechnicalObject", "TechnicalObject")
                        .WithMany("TechnologicalUnits")
                        .HasForeignKey("TechnicalObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Workshop", "Workshop")
                        .WithMany("TechnologicalUnits")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnicalObject");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Workshop", b =>
                {
                    b.HasOne("kursovou_wed.models.User", "ResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ResponsiblePerson");
                });

            modelBuilder.Entity("kursovou_wed.models.Request", b =>
                {
                    b.HasOne("kursovou_wed.models.User", "Assignee")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("AssigneeId");

                    b.HasOne("kursovou_wed.models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentInstance", "EquipmentInstance")
                        .WithMany()
                        .HasForeignKey("EquipmentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalObject", "TechnicalObject")
                        .WithMany()
                        .HasForeignKey("TechnicalObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnologicalUnit", "TechnologicalUnit")
                        .WithMany()
                        .HasForeignKey("TechnologicalUnitId");

                    b.HasOne("Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Creator");

                    b.Navigation("EquipmentInstance");

                    b.Navigation("TechnicalObject");

                    b.Navigation("TechnologicalUnit");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Complex", b =>
                {
                    b.Navigation("TechnicalObjects");
                });

            modelBuilder.Entity("EquipmentInstance", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("EquipmentType", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("TechnicalObject", b =>
                {
                    b.Navigation("EquipmentInstances");

                    b.Navigation("TechnologicalUnits");
                });

            modelBuilder.Entity("TechnologicalUnit", b =>
                {
                    b.Navigation("EquipmentInstances");
                });

            modelBuilder.Entity("Workshop", b =>
                {
                    b.Navigation("TechnologicalUnits");
                });

            modelBuilder.Entity("kursovou_wed.models.User", b =>
                {
                    b.Navigation("AssignedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
